import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { getTestimonials } from './services/testimonialsService'
import { getUseCases } from './services/useCasesService'
import { submitLead } from './services/leadService'
import './styles.css'

const A='/Test-tarea-3/'
const assets='https://snapbuild.ru/assets/images/'

function Logo(){return <img className="logo" src={`${A}images/snapbuild-logo.svg`} alt="Снэпбилд"/>}
function Header(){const[open,setOpen]=useState(false);return <header className="top"><div className="topbar"><a href="#top"><Logo/></a><button className="menu" onClick={()=>setOpen(!open)}>{open?'Закрыть':'Меню'}</button><nav className={open?'open':''} onClick={()=>setOpen(false)}><a href="#product">Продукт</a><a href="#features">Возможности</a><a href="#security">Безопасность</a><a href="#faq">FAQ</a></nav><a className="btn compact" href="#contact">Начать сейчас</a></div></header>}
const Btn=({children='Начать сейчас',href='#contact',light=false})=><a href={href} className={`btn ${light?'light':''}`}>{children}</a>
function Hero(){return <section className="hero" id="top"><div className="hero-text"><h1>Платформа, где все создается в рамках вашего бренда и дизайн-системы</h1><p>Подключите дизайн-систему к Снэпбилду, чтобы каждый участник команды мог создавать профессиональные материалы в фирменном стиле за минуты, а не дни.</p><Btn/></div><div className="hero-shot"><img src={`${A}images/hero.webp`} alt="Интерфейс платформы Снэпбилд"/></div></section>}
function BrandLine(){return <div className="brandline"><span>С платформой работают команды, для которых бренд — закон</span><div className="brands"><b>IVI</b><b>WB</b><b>OZON</b><b>МТС</b><b>VK</b></div></div>}
const Head=({children,copy})=><div className="head"><h2>{children}</h2>{copy&&<p>{copy}</p>}</div>

const platform=[
 {n:'01',title:'Дизайн-система — ядро платформы',text:'Ваши компоненты, цвета и шрифты — единственный источник стиля',img:'84a4450b3827bc21.webp'},
 {n:'02',title:'Гибкая конфигурация',text:'Правила бренда задаются один раз — работают в каждой генерации',img:'process-flexible-configuration.webp'},
 {n:'03',title:'Соответствие по умолчанию',text:'AI не может нарушить бренд: материалы создаются строго по вашим правилам',img:'afe03eb4a67d5dfb.webp'}]
function Platform(){return <section id="product"><Head copy="Сайты, изображения, видео, баннеры и презентации — из одной идеи, в вашем стиле">Одна платформа — весь маркетинг</Head><div className="platform-grid">{platform.map(x=><article className="platform-card" key={x.n}><div className="card-copy"><span>{x.n}</span><h3>{x.title}</h3><p>{x.text}</p></div><img src={`${assets}${x.img}`} alt=""/></article>)}</div></section>}

const featureData={
 'Сайты':{img:'use-cases-tab1-item1-v2.webp',items:[['Результат за один запрос','Отправляйте документ или ссылку — платформа собирает структуру'],['Страница за минуту','В вашей дизайн-системе, с вашими шрифтами и компонентами'],['AI или визуальный редактор','Меняйте контент через чат или редактируйте вручную'],['Адаптация под ЦА за один клик','Версия сайта под новый сегмент без команды продакшена']]},
 'Изображения':{img:'use-cases-img-01.webp',items:[['В стиле и цвете бренда','Единый визуальный язык во всех генерациях'],['Попадание с первой генерации','Меньше итераций и ручных правок'],['Редактирование объектов','Меняйте отдельные детали без пересборки']]},
 'Видео':{img:'use-cases-vid-01.webp',items:[['Любой стиль и формат','Ролики для каждой платформы'],['Ключевые кадры под контролем','Согласуйте композицию до генерации'],['Версии автоматически','Один сценарий — десятки адаптаций']]},
 'Баннеры':{img:'use-cases-tab4-item1.webp',items:[['Креативы из одной идеи','Мастер-макет для всей кампании'],['Все размеры автоматически','Адаптации под площадки и плейсменты'],['Экспорт под площадку','Готовые форматы без ручной сборки']]},
 'Презентации':{img:'use-cases-pres-01.jpg',items:[['Презентация из запроса','Готовая структура и визуальный рассказ'],['В вашей дизайн-системе','Компоненты, сетка и типографика бренда'],['Редактирование через AI','Обновляйте содержание в диалоге']]}}
function Features(){const[tab,setTab]=useState('Сайты');const data=featureData[tab];return <section id="features"><Head>Любой контент в фирменном стиле за считанные минуты</Head><div className="tabs">{Object.keys(featureData).map(x=><button className={x===tab?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="feature-panel"><div className="feature-list">{data.items.map((x,i)=><div className={i===0?'active':''} key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div><div className="feature-image"><img src={`${assets}${data.img}`} alt="Пример материала в Снэпбилде"/></div></div></section>}

const compare=[['Time-to-market','5 минут','30–60 мин','2–3 дня','1–2 дня','3–5 недель'],['Дизайн-система','100% точность','Частично','Шаблоны','Вручную','Через ревью'],['Визуальный редактор','+ ИИ','—','+','—','—'],['Требуемые навыки','Нет','Промпты + код','Дизайн','Разработка','Полная команда']]
function Comparison(){return <section><Head copy="Вы получаете не редактор, а результат: готовые маркетинговые материалы без проблем с настройками">Почему команды выбирают Снэпбилд</Head><div className="table-wrap"><table><thead><tr><th>Особенности</th><th className="selected">снэпбилд</th><th>Claude + Figma MCP</th><th>No-code</th><th>Cursor</th><th>Традиционный</th></tr></thead><tbody>{compare.map(r=><tr key={r[0]}>{r.map((c,i)=><td className={i===1?'selected':''} key={i}>{c}</td>)}</tr>)}</tbody></table></div></section>}

function Cases(){const[items,setItems]=useState([]),[active,setActive]=useState(0),[state,setState]=useState('loading');useEffect(()=>{getUseCases().then(data=>{setItems(data);setState('data')}).catch(()=>setState('error'))},[]);const item=items[active];return <section id="cases" className="added use-cases"><Head copy="Маркетинг, дизайн, продажи и продукт используют одну платформу — каждый для своих задач">Кейсы использования</Head>{state==='loading'&&<div className="case-panel case-state">Загружаем кейсы…</div>}{state==='error'&&<div className="case-panel case-state">Не удалось загрузить кейсы.</div>}{item&&<><div className="case-tabs" role="tablist">{items.map((x,i)=><button role="tab" aria-selected={i===active} className={i===active?'active':''} onClick={()=>setActive(i)} key={x.id}>{x.tab}</button>)}</div><article className="case-panel"><div className="case-main"><span>0{active+1} / 04</span><h3>{item.title}</h3><p>{item.text}</p></div><ul>{item.points.map(x=><li key={x}>↗ <span>{x}</span></li>)}</ul><div className="case-metric"><strong>{item.metric}</strong><span>{item.metricLabel}</span></div></article></>}</section>}
function Metrics(){return <section id="metrics" className="added metrics"><Head>Результат, который можно измерить</Head><div className="metric-grid">{[['5 минут','до первой версии'],['100%','соответствие дизайн-системе'],['78%','меньше ручных правок'],['6×','больше материалов']].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><p className="note">Средние показатели проектных команд после внедрения платформы</p></section>}
function Testimonials(){const[items,setItems]=useState([]),[n,setN]=useState(0),[state,setState]=useState('loading'),[retry,setRetry]=useState(0);useEffect(()=>{let live=true;setState('loading');getTestimonials().then(data=>{if(live){setItems(data);setState('data')}}).catch(()=>live&&setState('error'));return()=>{live=false}},[retry]);return <section className="added reviews"><Head copy="Данные приходят из JSON через отдельный service layer — источник можно заменить API без изменения компонента">Команды о работе со Снэпбилдом</Head>{state==='loading'&&<div className="review loading">Загружаем отзывы…</div>}{state==='error'&&<div className="review loading">Не удалось загрузить отзывы.<button onClick={()=>setRetry(retry+1)}>Повторить</button></div>}{state==='data'&&items.length>0&&<article className="review"><blockquote>«{items[n].quote}»</blockquote><div className="review-foot"><div className="avatar">{items[n].initials}</div><div><b>{items[n].name}</b><span>{items[n].role}</span></div><div className="review-nav"><span>{n+1} / {items.length}</span><button aria-label="Предыдущий отзыв" onClick={()=>setN((n-1+items.length)%items.length)}>←</button><button aria-label="Следующий отзыв" onClick={()=>setN((n+1)%items.length)}>→</button></div></div></article>}</section>}
const plans=[{name:'Команда',month:49000,year:470000,text:'Для одного отдела маркетинга',features:['До 5 пользователей','1 дизайн-система','Сайты и изображения']},{name:'Бизнес',month:129000,year:1238000,text:'Для производства контента в масштабе',features:['До 25 пользователей','Все форматы','Роли и согласования'],hot:true},{name:'Контур',month:null,year:null,text:'Для корпоративной инфраструктуры',features:['Без ограничений','Private cloud / on-premise','Собственные модели и SSO']}]
function Pricing(){const[period,setPeriod]=useState('month');const price=p=>p[period]?`${p[period].toLocaleString('ru-RU')} ₽`:'По запросу';return <section id="pricing" className="added"><div className="pricing-head"><Head copy="При оплате за год два месяца работы включены в стоимость">Тарифы под ваши задачи</Head><div className="billing" aria-label="Период оплаты"><button className={period==='month'?'active':''} onClick={()=>setPeriod('month')}>Месяц</button><button className={period==='year'?'active':''} onClick={()=>setPeriod('year')}>Год <span>−20%</span></button></div></div><div className="prices">{plans.map(p=><article className={p.hot?'hot':''} key={p.name}>{p.hot&&<small>Популярный</small>}<h3>{p.name}</h3><p>{p.text}</p><strong>{price(p)}{p[period]&&<small> / {period==='month'?'месяц':'год'}</small>}</strong><ul>{p.features.map(x=><li key={x}>✓ {x}</li>)}</ul><Btn>{p.name==='Контур'?'Обсудить проект':'Запросить демо'}</Btn></article>)}</div></section>}

const security=[['Только одобренные модели','Работаем только с российскими и локализованными моделями, без экспортных ограничений','security-approved-models.webp'],['Ваш контур, ваша юрисдикция','Развертывание в частном облаке с полным соответствием 152-ФЗ и внутренним ИБ-требованиям','security-private-cloud.webp'],['Собственный AI-стек','Вы сами определяете модели, хранилища, доступы и цепочки валидации','security-ai-stack.webp']]
function Security(){return <section id="security"><Head>Безопасность без компромиссов</Head><div className="security-grid">{security.map((x,i)=><article key={x[0]}><img src={`${assets}${x[2]}`} alt=""/><div><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></section>}
const roadmap=[['Сайты за 5 минут','Декабрь, 2025'],['Консистентные AI-иллюстрации','Январь, 2026'],['Дизайн-система из вашего сайта','Февраль, 2026'],['Режим изображений','Март, 2026'],['Генерация видео','Апрель, 2026'],['Канвас, баннеры и презентации','Июль, 2026']]
function Roadmap(){return <section className="roadmap"><Head copy="Приоритизируем бэклог для ваших целей">Каждый день — новый релиз</Head><div className="road-list">{roadmap.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><small>{x[1]}</small></article>)}</div></section>}
const faq=[['Что можно создавать в Снэпбилде?','Сайты, изображения, видео, баннеры и презентации — все основные форматы маркетинговых материалов в едином фирменном стиле.'],['Как работает анализ бренда?','Система анализирует интерфейсы и компоненты, выделяет цвета, типографику, сетки и формирует модель дизайн-системы.'],['Можно ли экспортировать решение?','Да. Результат пригоден для интеграции в React, Vue, Angular или чистый HTML/CSS и текущий CI/CD.'],['Возможна ли работа в закрытом облаке?','Да. Поддерживается развёртывание в изолированной инфраструктуре без доступа к внешней сети.']]
function FAQ(){const[open,setOpen]=useState(0);return <section id="faq"><Head copy="Ответы, которые помогут принять решение уверенно — без рисков для бренда и безопасности">Часто задаваемые вопросы</Head><div className="faq-list">{faq.map((x,i)=><article className={open===i?'open':''} key={x[0]}><button onClick={()=>setOpen(open===i?-1:i)}><span>{x[0]}</span><b>{open===i?'−':'+'}</b></button>{open===i&&<p>{x[1]}</p>}</article>)}</div></section>}
function Contact(){const[form,setForm]=useState({name:'',email:'',company:''}),[errors,setErrors]=useState({}),[state,setState]=useState('idle');const submit=async e=>{e.preventDefault();const er={};if(!form.name.trim())er.name='Укажите имя';if(!/^\S+@\S+\.\S+$/.test(form.email))er.email='Введите корректный email';if(!form.company.trim())er.company='Укажите компанию';setErrors(er);if(Object.keys(er).length)return;setState('loading');try{await submitLead(form);setState('success')}catch{setState('error')}};const field=(key,label,type='text')=><label>{label}<input type={type} value={form[key]} aria-invalid={!!errors[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>{errors[key]&&<small>{errors[key]}</small>}</label>;return <section className="added contact-form" id="contact"><Head copy="Оставьте контакты — проведём персональную демонстрацию на материалах вашей компании">Посмотрим на задачи вашей команды</Head><div className="formbox">{state==='success'?<div className="success"><b>✓</b><h3>Заявка принята</h3><p>Свяжемся с вами в течение рабочего дня.</p><button onClick={()=>setState('idle')}>Отправить ещё одну</button></div>:<form onSubmit={submit} noValidate>{field('name','Ваше имя')}{field('email','Рабочий email','email')}{field('company','Компания')}<button className="btn" disabled={state==='loading'}>{state==='loading'?'Отправляем…':'Запросить демо'}</button>{state==='error'&&<small>Не удалось отправить. Попробуйте ещё раз.</small>}<p>Нажимая кнопку, вы соглашаетесь с политикой конфиденциальности</p></form>}</div></section>}
function FinalCTA(){return <section className="final-cta"><h2>Профессиональные материалы в фирменном стиле<br/>за минуты, а не дни</h2><Btn light>Начать сейчас</Btn></section>}
function Footer(){return <footer><div><Logo/><p>Платформа, где все создается в рамках вашего бренда и дизайн-системы</p></div><div><b>Навигация</b><a href="#product">Продукт</a><a href="#features">Возможности</a><a href="#security">Безопасность</a><a href="#faq">FAQ</a></div><div><b>Контакты</b><a href="mailto:hey@snapbuild.ru">hey@snapbuild.ru</a><a href="#contact">Запросить демо</a></div><span>© Сгенерировано в Снэпбилде. Все права защищены.</span></footer>}
function App(){return <><Header/><main><Hero/><BrandLine/><Platform/><Features/><Cases/><Comparison/><Metrics/><Security/><Roadmap/><Testimonials/><Pricing/><FAQ/><Contact/><FinalCTA/></main><Footer/></>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>)
